// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskManagmentService.App.Infrastructure;

#nullable disable

namespace TaskManagmentService.App.Infrastructure.Migrations
{
    [DbContext(typeof(ServiceContext))]
    [Migration("20251116090834_FixProjectIds")]
    partial class FixProjectIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskManagmentService.App.Domain.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignmentGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_group_id");

                    b.Property<string>("AssignmentStatus")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assignment_status");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DeadlineUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("assignment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AssignmentStatus = "Backlog",
                            CreatedAtUtc = new DateTime(2025, 11, 15, 0, 5, 0, 0, DateTimeKind.Utc),
                            DeadlineUtc = new DateTime(2025, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description1",
                            Priority = "Medium",
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Title = "Title1"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AssignmentStatus = "Backlog",
                            CreatedAtUtc = new DateTime(2025, 11, 15, 0, 10, 0, 0, DateTimeKind.Utc),
                            DeadlineUtc = new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description2",
                            Priority = "Medium",
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Title = "Title2"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AssignmentStatus = "Backlog",
                            CreatedAtUtc = new DateTime(2025, 11, 15, 0, 15, 0, 0, DateTimeKind.Utc),
                            DeadlineUtc = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description3",
                            Priority = "Medium",
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Title = "Title3"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111112"),
                            AssignmentStatus = "Backlog",
                            CreatedAtUtc = new DateTime(2025, 11, 15, 0, 20, 0, 0, DateTimeKind.Utc),
                            DeadlineUtc = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description4",
                            Priority = "Medium",
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Title = "Title4"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111112"),
                            AssignmentStatus = "Backlog",
                            CreatedAtUtc = new DateTime(2025, 11, 15, 0, 25, 0, 0, DateTimeKind.Utc),
                            DeadlineUtc = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description5",
                            Priority = "Medium",
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Title = "Title5"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111116"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111112"),
                            AssignmentStatus = "Backlog",
                            CreatedAtUtc = new DateTime(2025, 11, 15, 0, 30, 0, 0, DateTimeKind.Utc),
                            DeadlineUtc = new DateTime(2025, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description6",
                            Priority = "Medium",
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Title = "Title6"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111117"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AssignmentStatus = "Backlog",
                            CreatedAtUtc = new DateTime(2025, 11, 15, 0, 35, 0, 0, DateTimeKind.Utc),
                            DeadlineUtc = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description7",
                            Priority = "Medium",
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222205"),
                            Title = "Title7"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111118"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AssignmentStatus = "Backlog",
                            CreatedAtUtc = new DateTime(2025, 11, 15, 0, 40, 0, 0, DateTimeKind.Utc),
                            DeadlineUtc = new DateTime(2025, 11, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description8",
                            Priority = "Medium",
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Title = "Title8"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111119"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111112"),
                            AssignmentStatus = "Backlog",
                            CreatedAtUtc = new DateTime(2025, 11, 15, 0, 45, 0, 0, DateTimeKind.Utc),
                            DeadlineUtc = new DateTime(2025, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description9",
                            Priority = "Medium",
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Title = "Title9"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111120"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111113"),
                            AssignmentStatus = "Backlog",
                            CreatedAtUtc = new DateTime(2025, 11, 15, 0, 50, 0, 0, DateTimeKind.Utc),
                            DeadlineUtc = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description10",
                            Priority = "Medium",
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Title = "Title10"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111121"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111112"),
                            AssignmentStatus = "Backlog",
                            CreatedAtUtc = new DateTime(2025, 11, 15, 0, 55, 0, 0, DateTimeKind.Utc),
                            DeadlineUtc = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description11",
                            Priority = "Medium",
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Title = "Title11"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111122"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111112"),
                            AssignmentStatus = "Backlog",
                            CreatedAtUtc = new DateTime(2025, 11, 15, 1, 0, 0, 0, DateTimeKind.Utc),
                            DeadlineUtc = new DateTime(2025, 11, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description12",
                            Priority = "Medium",
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Title = "Title12"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111123"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111113"),
                            AssignmentStatus = "Backlog",
                            CreatedAtUtc = new DateTime(2025, 11, 15, 1, 5, 0, 0, DateTimeKind.Utc),
                            DeadlineUtc = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description13",
                            Priority = "Medium",
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222204"),
                            Title = "Title13"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111124"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111114"),
                            AssignmentStatus = "Backlog",
                            CreatedAtUtc = new DateTime(2025, 11, 15, 1, 10, 0, 0, DateTimeKind.Utc),
                            DeadlineUtc = new DateTime(2025, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description14",
                            Priority = "Medium",
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Title = "Title14"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111125"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111115"),
                            AssignmentStatus = "Backlog",
                            CreatedAtUtc = new DateTime(2025, 11, 15, 1, 15, 0, 0, DateTimeKind.Utc),
                            DeadlineUtc = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description15",
                            Priority = "Medium",
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Title = "Title15"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111126"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111112"),
                            AssignmentStatus = "Backlog",
                            CreatedAtUtc = new DateTime(2025, 11, 15, 1, 20, 0, 0, DateTimeKind.Utc),
                            DeadlineUtc = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description16",
                            Priority = "Medium",
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Title = "Title16"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111127"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111112"),
                            AssignmentStatus = "Backlog",
                            CreatedAtUtc = new DateTime(2025, 11, 15, 1, 25, 0, 0, DateTimeKind.Utc),
                            DeadlineUtc = new DateTime(2025, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description17",
                            Priority = "Medium",
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Title = "Title17"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111128"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AssignmentStatus = "Backlog",
                            CreatedAtUtc = new DateTime(2025, 11, 15, 1, 30, 0, 0, DateTimeKind.Utc),
                            DeadlineUtc = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description18",
                            Priority = "Medium",
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Title = "Title18"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111129"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AssignmentStatus = "Backlog",
                            CreatedAtUtc = new DateTime(2025, 11, 15, 1, 35, 0, 0, DateTimeKind.Utc),
                            DeadlineUtc = new DateTime(2025, 12, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description19",
                            Priority = "Medium",
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Title = "Title19"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111130"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AssignmentStatus = "Backlog",
                            CreatedAtUtc = new DateTime(2025, 11, 15, 1, 40, 0, 0, DateTimeKind.Utc),
                            DeadlineUtc = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description20",
                            Priority = "Medium",
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Title = "Title20"
                        });
                });

            modelBuilder.Entity("TaskManagmentService.App.Domain.Entities.AssignmentEmployee", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("AssignmentRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assignment_role");

                    b.HasKey("AssignmentId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("assignment_employee", (string)null);

                    b.HasData(
                        new
                        {
                            AssignmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EmployeeId = new Guid("11111111-1111-1111-1111-111111111118"),
                            AssignmentRole = "Executor"
                        },
                        new
                        {
                            AssignmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EmployeeId = new Guid("11111111-1111-1111-1111-111111111119"),
                            AssignmentRole = "Executor"
                        },
                        new
                        {
                            AssignmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EmployeeId = new Guid("11111111-1111-1111-1111-111111111114"),
                            AssignmentRole = "Observer"
                        },
                        new
                        {
                            AssignmentId = new Guid("11111111-1111-1111-1111-111111111112"),
                            EmployeeId = new Guid("11111111-1111-1111-1111-111111111120"),
                            AssignmentRole = "Executor"
                        },
                        new
                        {
                            AssignmentId = new Guid("11111111-1111-1111-1111-111111111112"),
                            EmployeeId = new Guid("11111111-1111-1111-1111-111111111115"),
                            AssignmentRole = "Observer"
                        },
                        new
                        {
                            AssignmentId = new Guid("11111111-1111-1111-1111-111111111113"),
                            EmployeeId = new Guid("11111111-1111-1111-1111-111111111121"),
                            AssignmentRole = "Executor"
                        },
                        new
                        {
                            AssignmentId = new Guid("11111111-1111-1111-1111-111111111113"),
                            EmployeeId = new Guid("11111111-1111-1111-1111-111111111116"),
                            AssignmentRole = "Observer"
                        },
                        new
                        {
                            AssignmentId = new Guid("11111111-1111-1111-1111-111111111114"),
                            EmployeeId = new Guid("11111111-1111-1111-1111-111111111122"),
                            AssignmentRole = "Executor"
                        },
                        new
                        {
                            AssignmentId = new Guid("11111111-1111-1111-1111-111111111114"),
                            EmployeeId = new Guid("11111111-1111-1111-1111-111111111117"),
                            AssignmentRole = "Observer"
                        },
                        new
                        {
                            AssignmentId = new Guid("11111111-1111-1111-1111-111111111114"),
                            EmployeeId = new Guid("11111111-1111-1111-1111-111111111125"),
                            AssignmentRole = "Observer"
                        },
                        new
                        {
                            AssignmentId = new Guid("11111111-1111-1111-1111-111111111115"),
                            EmployeeId = new Guid("11111111-1111-1111-1111-111111111123"),
                            AssignmentRole = "Executor"
                        },
                        new
                        {
                            AssignmentId = new Guid("11111111-1111-1111-1111-111111111115"),
                            EmployeeId = new Guid("11111111-1111-1111-1111-111111111126"),
                            AssignmentRole = "Observer"
                        },
                        new
                        {
                            AssignmentId = new Guid("11111111-1111-1111-1111-111111111116"),
                            EmployeeId = new Guid("11111111-1111-1111-1111-111111111124"),
                            AssignmentRole = "Executor"
                        },
                        new
                        {
                            AssignmentId = new Guid("11111111-1111-1111-1111-111111111117"),
                            EmployeeId = new Guid("11111111-1111-1111-1111-111111111127"),
                            AssignmentRole = "Executor"
                        },
                        new
                        {
                            AssignmentId = new Guid("11111111-1111-1111-1111-111111111117"),
                            EmployeeId = new Guid("11111111-1111-1111-1111-111111111128"),
                            AssignmentRole = "Observer"
                        },
                        new
                        {
                            AssignmentId = new Guid("11111111-1111-1111-1111-111111111118"),
                            EmployeeId = new Guid("11111111-1111-1111-1111-111111111129"),
                            AssignmentRole = "Executor"
                        },
                        new
                        {
                            AssignmentId = new Guid("11111111-1111-1111-1111-111111111119"),
                            EmployeeId = new Guid("11111111-1111-1111-1111-111111111130"),
                            AssignmentRole = "Executor"
                        },
                        new
                        {
                            AssignmentId = new Guid("11111111-1111-1111-1111-111111111119"),
                            EmployeeId = new Guid("11111111-1111-1111-1111-111111111118"),
                            AssignmentRole = "Observer"
                        },
                        new
                        {
                            AssignmentId = new Guid("11111111-1111-1111-1111-111111111120"),
                            EmployeeId = new Guid("11111111-1111-1111-1111-111111111119"),
                            AssignmentRole = "Executor"
                        },
                        new
                        {
                            AssignmentId = new Guid("11111111-1111-1111-1111-111111111120"),
                            EmployeeId = new Guid("11111111-1111-1111-1111-111111111120"),
                            AssignmentRole = "Observer"
                        });
                });

            modelBuilder.Entity("TaskManagmentService.App.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("employee", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Role = "MANAGER",
                            Username = "ivanov.ap"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Role = "MANAGER",
                            Username = "petrova.ms"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            Role = "MANAGER",
                            Username = "sidorov.di"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            Role = "ANALYST",
                            Username = "kozlova.av"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            Role = "ANALYST",
                            Username = "fedorov.mo"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111116"),
                            Role = "ANALYST",
                            Username = "nikitina.ed"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111117"),
                            Role = "ANALYST",
                            Username = "orlov.sv"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111118"),
                            Role = "DEVELOPER",
                            Username = "volkov.aa"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111119"),
                            Role = "DEVELOPER",
                            Username = "zaitseva.oi"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111120"),
                            Role = "DEVELOPER",
                            Username = "pavlov.is"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111121"),
                            Role = "DEVELOPER",
                            Username = "semenova.tp"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111122"),
                            Role = "DEVELOPER",
                            Username = "morozov.av"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111123"),
                            Role = "DEVELOPER",
                            Username = "alekseev.vn"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111124"),
                            Role = "DEVELOPER",
                            Username = "kovaleva.ya"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111125"),
                            Role = "QA",
                            Username = "grigorev.po"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111126"),
                            Role = "QA",
                            Username = "belova.nv"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111127"),
                            Role = "QA",
                            Username = "kiselev.ad"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111128"),
                            Role = "QA",
                            Username = "sokolova.ia"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111129"),
                            Role = "QA",
                            Username = "titov.rm"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111130"),
                            Role = "QA",
                            Username = "medvedeva.sg"
                        });
                });

            modelBuilder.Entity("TaskManagmentService.App.Domain.Entities.AssignmentEmployee", b =>
                {
                    b.HasOne("TaskManagmentService.App.Domain.Entities.Assignment", "Assignment")
                        .WithMany("AssignmentEmployees")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManagmentService.App.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TaskManagmentService.App.Domain.Entities.Assignment", b =>
                {
                    b.Navigation("AssignmentEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
