// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskManagmentService.App.Infrastructure;

#nullable disable

namespace TaskManagmentService.App.Infrastructure.Migrations
{
    [DbContext(typeof(ServiceContext))]
    [Migration("20251113140613_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskManagmentService.App.Domain.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignmentGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_group_id");

                    b.Property<string>("AssignmentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assignment_status");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DeadLineUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("assignment", (string)null);
                });

            modelBuilder.Entity("TaskManagmentService.App.Domain.Entities.AssignmentEmployee", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("AssignmentRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assignment_role");

                    b.HasKey("AssignmentId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("assignment_employee", (string)null);
                });

            modelBuilder.Entity("TaskManagmentService.App.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("employee", (string)null);
                });

            modelBuilder.Entity("TaskManagmentService.App.Domain.Entities.AssignmentEmployee", b =>
                {
                    b.HasOne("TaskManagmentService.App.Domain.Entities.Assignment", "Assignment")
                        .WithMany("AssignmentEmployees")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManagmentService.App.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TaskManagmentService.App.Domain.Entities.Assignment", b =>
                {
                    b.Navigation("AssignmentEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
