// <auto-generated />
using System;
using EmployeesService.App.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmployeesService.App.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251113061753_SeedDataToTable")]
    partial class SeedDataToTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeesService.App.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("patronymic");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("surname");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("employee", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Алексей",
                            Patronymic = "Петрович",
                            Role = "MANAGER",
                            Surname = "Иванов",
                            Username = "ivanov.ap"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Name = "Мария",
                            Patronymic = "Сергеевна",
                            Role = "MANAGER",
                            Surname = "Петрова",
                            Username = "petrova.ms"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            Name = "Дмитрий",
                            Patronymic = "Игоревич",
                            Role = "MANAGER",
                            Surname = "Сидоров",
                            Username = "sidorov.di"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            Name = "Анна",
                            Patronymic = "Владимировна",
                            Role = "ANALYST",
                            Surname = "Козлова",
                            Username = "kozlova.av"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            Name = "Михаил",
                            Patronymic = "Олегович",
                            Role = "ANALYST",
                            Surname = "Федоров",
                            Username = "fedorov.mo"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111116"),
                            Name = "Елена",
                            Patronymic = "Дмитриевна",
                            Role = "ANALYST",
                            Surname = "Никитина",
                            Username = "nikitina.ed"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111117"),
                            Name = "Сергей",
                            Patronymic = "Викторович",
                            Role = "ANALYST",
                            Surname = "Орлов",
                            Username = "orlov.sv"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111118"),
                            Name = "Андрей",
                            Patronymic = "Александрович",
                            Role = "DEVELOPER",
                            Surname = "Волков",
                            Username = "volkov.aa"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111119"),
                            Name = "Ольга",
                            Patronymic = "Ивановна",
                            Role = "DEVELOPER",
                            Surname = "Зайцева",
                            Username = "zaitseva.oi"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111120"),
                            Name = "Игорь",
                            Patronymic = "Сергеевич",
                            Role = "DEVELOPER",
                            Surname = "Павлов",
                            Username = "pavlov.is"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111121"),
                            Name = "Татьяна",
                            Patronymic = "Петровна",
                            Role = "DEVELOPER",
                            Surname = "Семенова",
                            Username = "semenova.tp"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111122"),
                            Name = "Артем",
                            Patronymic = "Вадимович",
                            Role = "DEVELOPER",
                            Surname = "Морозов",
                            Username = "morozov.av"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111123"),
                            Name = "Владимир",
                            Patronymic = "Николаевич",
                            Role = "DEVELOPER",
                            Surname = "Алексеев",
                            Username = "alekseev.vn"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111124"),
                            Name = "Юлия",
                            Patronymic = "Андреевна",
                            Role = "DEVELOPER",
                            Surname = "Ковалева",
                            Username = "kovaleva.ya"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111125"),
                            Name = "Павел",
                            Patronymic = "Олегович",
                            Role = "QA",
                            Surname = "Григорьев",
                            Username = "grigorev.po"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111126"),
                            Name = "Наталья",
                            Patronymic = "Викторовна",
                            Role = "QA",
                            Surname = "Белова",
                            Username = "belova.nv"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111127"),
                            Name = "Антон",
                            Patronymic = "Денисович",
                            Role = "QA",
                            Surname = "Киселев",
                            Username = "kiselev.ad"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111128"),
                            Name = "Ирина",
                            Patronymic = "Алексеевна",
                            Role = "QA",
                            Surname = "Соколова",
                            Username = "sokolova.ia"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111129"),
                            Name = "Роман",
                            Patronymic = "Михайлович",
                            Role = "QA",
                            Surname = "Титов",
                            Username = "titov.rm"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111130"),
                            Name = "Светлана",
                            Patronymic = "Геннадьевна",
                            Role = "QA",
                            Surname = "Медведева",
                            Username = "medvedeva.sg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
