// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectManagementService.App.Infrastructure;

#nullable disable

namespace ProjectManagementService.App.Infrastructure.Migrations
{
    [DbContext(typeof(ServiceContext))]
    [Migration("20251116091114_FillTables")]
    partial class FillTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectManagementService.App.Domain.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111116"),
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111117"),
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222205"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111118"),
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111119"),
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111120"),
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111121"),
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111122"),
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111123"),
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222204"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111124"),
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111125"),
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111126"),
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111127"),
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111128"),
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111129"),
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111130"),
                            ProjectId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Status = "Backlog"
                        });
                });

            modelBuilder.Entity("ProjectManagementService.App.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Role = "MANAGER",
                            Username = "ivanov.ap"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Role = "MANAGER",
                            Username = "petrova.ms"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            Role = "MANAGER",
                            Username = "sidorov.di"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            Role = "ANALYST",
                            Username = "kozlova.av"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            Role = "ANALYST",
                            Username = "fedorov.mo"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111116"),
                            Role = "ANALYST",
                            Username = "nikitina.ed"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111117"),
                            Role = "ANALYST",
                            Username = "orlov.sv"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111118"),
                            Role = "DEVELOPER",
                            Username = "volkov.aa"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111119"),
                            Role = "DEVELOPER",
                            Username = "zaitseva.oi"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111120"),
                            Role = "DEVELOPER",
                            Username = "pavlov.is"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111121"),
                            Role = "DEVELOPER",
                            Username = "semenova.tp"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111122"),
                            Role = "DEVELOPER",
                            Username = "morozov.av"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111123"),
                            Role = "DEVELOPER",
                            Username = "alekseev.vn"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111124"),
                            Role = "DEVELOPER",
                            Username = "kovaleva.ya"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111125"),
                            Role = "QA",
                            Username = "grigorev.po"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111126"),
                            Role = "QA",
                            Username = "belova.nv"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111127"),
                            Role = "QA",
                            Username = "kiselev.ad"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111128"),
                            Role = "QA",
                            Username = "sokolova.ia"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111129"),
                            Role = "QA",
                            Username = "titov.rm"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111130"),
                            Role = "QA",
                            Username = "medvedeva.sg"
                        });
                });

            modelBuilder.Entity("ProjectManagementService.App.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("SupervisorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            Description = "Description1",
                            ManagerId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Name = "Name1",
                            SupervisorId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            Description = "Description2",
                            ManagerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Name2",
                            SupervisorId = new Guid("11111111-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222203"),
                            Description = "Description3",
                            ManagerId = new Guid("11111111-1111-1111-1111-111111111113"),
                            Name = "Name3",
                            SupervisorId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222204"),
                            Description = "Description4",
                            ManagerId = new Guid("11111111-1111-1111-1111-111111111113"),
                            Name = "Name4",
                            SupervisorId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222205"),
                            Description = "Description5",
                            ManagerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Name5",
                            SupervisorId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222206"),
                            Description = "Description6",
                            ManagerId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Name = "Name6",
                            SupervisorId = new Guid("11111111-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222207"),
                            Description = "Description7",
                            ManagerId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Name = "Name7",
                            SupervisorId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222208"),
                            Description = "Description8",
                            ManagerId = new Guid("11111111-1111-1111-1111-111111111113"),
                            Name = "Name8",
                            SupervisorId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222209"),
                            Description = "Description9",
                            ManagerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Name9",
                            SupervisorId = new Guid("11111111-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222210"),
                            Description = "Description10",
                            ManagerId = new Guid("11111111-1111-1111-1111-111111111113"),
                            Name = "Name10",
                            SupervisorId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222211"),
                            Description = "Description11",
                            ManagerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Name11",
                            SupervisorId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222212"),
                            Description = "Description12",
                            ManagerId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Name = "Name12",
                            SupervisorId = new Guid("11111111-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222213"),
                            Description = "Description13",
                            ManagerId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Name = "Name13",
                            SupervisorId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222214"),
                            Description = "Description14",
                            ManagerId = new Guid("11111111-1111-1111-1111-111111111113"),
                            Name = "Name14",
                            SupervisorId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222215"),
                            Description = "Description15",
                            ManagerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Name15",
                            SupervisorId = new Guid("11111111-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222216"),
                            Description = "Description16",
                            ManagerId = new Guid("11111111-1111-1111-1111-111111111113"),
                            Name = "Name16",
                            SupervisorId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222217"),
                            Description = "Description17",
                            ManagerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Name17",
                            SupervisorId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222218"),
                            Description = "Description18",
                            ManagerId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Name = "Name18",
                            SupervisorId = new Guid("11111111-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222219"),
                            Description = "Description19",
                            ManagerId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Name = "Name19",
                            SupervisorId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222220"),
                            Description = "Description20",
                            ManagerId = new Guid("11111111-1111-1111-1111-111111111113"),
                            Name = "Name20",
                            SupervisorId = new Guid("11111111-1111-1111-1111-111111111112")
                        });
                });

            modelBuilder.Entity("ProjectManagementService.App.Domain.Entities.Assignment", b =>
                {
                    b.HasOne("ProjectManagementService.App.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectManagementService.App.Domain.Entities.Project", b =>
                {
                    b.HasOne("ProjectManagementService.App.Domain.Entities.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("ProjectManagementService.App.Domain.Entities.Employee", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Supervisor");
                });
#pragma warning restore 612, 618
        }
    }
}
