// <auto-generated />
using System;
using AssignmentGroupManagemetService.App.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssignmentGroupManagemetService.App.Infrastructure.Migrations
{
    [DbContext(typeof(ServiceContext))]
    [Migration("20251116180923_Final")]
    partial class Final
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssignmentGroupManagemetService.App.Domain.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignmentGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentGroupId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111116"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111117"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111118"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111119"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111120"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111113"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111121"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111122"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111123"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111113"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111124"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111114"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111125"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111115"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111126"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111127"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111128"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111129"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111130"),
                            AssignmentGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "Backlog"
                        });
                });

            modelBuilder.Entity("AssignmentGroupManagemetService.App.Domain.Entities.AssignmentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("AssignmentGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Name1"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Name = "Name2"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            Name = "Name3"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            Name = "Name4"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            Name = "Name5"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111116"),
                            Name = "Name6"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111117"),
                            Name = "Name7"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111118"),
                            Name = "Name8"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111119"),
                            Name = "Name9"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111120"),
                            Name = "Name10"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111121"),
                            Name = "Name11"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111122"),
                            Name = "Name12"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111123"),
                            Name = "Name13"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111124"),
                            Name = "Name14"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111125"),
                            Name = "Name15"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111126"),
                            Name = "Name16"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111127"),
                            Name = "Name17"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111128"),
                            Name = "Name18"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111129"),
                            Name = "Name19"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111130"),
                            Name = "Name20"
                        });
                });

            modelBuilder.Entity("AssignmentGroupManagemetService.App.Domain.Entities.Assignment", b =>
                {
                    b.HasOne("AssignmentGroupManagemetService.App.Domain.Entities.AssignmentGroup", null)
                        .WithMany()
                        .HasForeignKey("AssignmentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
